version: "3.8"

services:

  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: Test2023
      POSTGRES_DB: etherium_service
      POSTGRES_USER: postgres
      POSTGRES_SSLMODE: disable
    ports:
      - "5432:5432"
    # (Left side): This is the port on your host machine : Right side): This is the port inside the Docker container that the service
    volumes:
      - ./dump/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    env_file:
      - .env
    build:
      context: ./
    ports:
      - 8080:8080



